<a href="https://colab.research.google.com/github/MeryemSulkhayeva/MeryemSulkhayeva/blob/main/Cifar10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlt
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

# (X_train_full, y_train_full), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()
# X_train,X_test, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.2)

(X_train_full, y_train_full), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()
X_train,X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, test_size=0.2, random_state=42)

170498071/170498071 [==============================] - 6s 0us/step


In [ ]:
X_train.shape, y_train.shape

((40000, 32, 32, 3), (40000, 1))

In [ ]:
# X_train = X_train/255.
# X_valid = X_valid / 255.0
# X_test = X_test / 255.0

In [ ]:
model = Sequential()
model.add(Flatten(input_shape=[32,32,3]))

for _ in range(20):
  model.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(10, activation='softmax'))

In [ ]:
optimizer = tf.keras.optimizers.Nadam(learning_rate=5e-5)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train[:5000], y_train[:5000], epochs=10, validation_data=(X_train, y_train))

Epoch 1/10
157/157 [==============================] - 18s 34ms/step - loss: 9.4004 - accuracy: 0.1012 - val_loss: 3.6268 - val_accuracy: 0.1106
Epoch 2/10
157/157 [==============================] - 4s 29ms/step - loss: 3.1546 - accuracy: 0.1202 - val_loss: 2.7666 - val_accuracy: 0.1281
Epoch 3/10
157/157 [==============================] - 4s 27ms/step - loss: 2.6116 - accuracy: 0.1358 - val_loss: 2.5377 - val_accuracy: 0.1354
Epoch 4/10
157/157 [==============================] - 5s 29ms/step - loss: 2.4206 - accuracy: 0.1522 - val_loss: 2.4486 - val_accuracy: 0.1559
Epoch 5/10
157/157 [==============================] - 4s 28ms/step - loss: 2.3227 - accuracy: 0.1794 - val_loss: 2.3239 - val_accuracy: 0.1708
Epoch 6/10
157/157 [==============================] - 4s 26ms/step - loss: 2.2479 - accuracy: 0.1962 - val_loss: 2.2382 - val_accuracy: 0.1816
Epoch 7/10
157/157 [==============================] - 5s 31ms/step - loss: 2.1923 - accuracy: 0.1980 - val_loss: 2.2062 - val_accuracy: 0.200

In [ ]:
X_train.shape, y_train.shape

((40000, 32, 32, 3), (40000, 1))

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience= 5, monitor='loss')

history = model.fit(X_train[:5000], y_train[:5000], epochs=100, callbacks=[early_stopping], validation_data=(X_train, y_train))

Epoch 1/100
157/157 [==============================] - 5s 34ms/step - loss: 2.0502 - accuracy: 0.2446 - val_loss: 2.1097 - val_accuracy: 0.2321
Epoch 2/100
157/157 [==============================] - 5s 31ms/step - loss: 2.0464 - accuracy: 0.2440 - val_loss: 2.1124 - val_accuracy: 0.2227
Epoch 3/100
157/157 [==============================] - 4s 27ms/step - loss: 2.0143 - accuracy: 0.2560 - val_loss: 2.0980 - val_accuracy: 0.2380
Epoch 4/100
157/157 [==============================] - 7s 43ms/step - loss: 2.0073 - accuracy: 0.2686 - val_loss: 2.1031 - val_accuracy: 0.2339
Epoch 5/100
157/157 [==============================] - 4s 27ms/step - loss: 1.9752 - accuracy: 0.2790 - val_loss: 2.0500 - val_accuracy: 0.2481
Epoch 6/100
157/157 [==============================] - 4s 27ms/step - loss: 1.9714 - accuracy: 0.2818 - val_loss: 2.0584 - val_accuracy: 0.2487
Epoch 7/100
157/157 [==============================] - 5s 30ms/step - loss: 1.9512 - accuracy: 0.2946 - val_loss: 2.0669 - val_accuracy:

In [ ]:
model.evaluate(X_train, y_train)

1250/1250 [==============================] - 4s 3ms/step - loss: 2.8406 - accuracy: 0.3720


[2.8406031131744385, 0.3719500005245209]

In [ ]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 6.4074 - accuracy: 0.1012


[6.407403945922852, 0.10119999945163727]

In [ ]:
tf.keras.backend.clear_session()
tf.random.set_seed(42)

In [ ]:
model = Sequential()
model.add(Flatten(input_shape=[32,32,3]))
model.add(tf.keras.layers.BatchNormalization())
for _ in range(20):
  model.add(Dense(100, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(10, activation='softmax'))


In [ ]:
optimizer = tf.keras.optimizers.Nadam(learning_rate=5e-5)
model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
model.fit(X_train[:5000], y_train[:5000],epochs=10, validation_data=(X_train, y_train))

Epoch 1/10
157/157 [==============================] - 15s 34ms/step - loss: 2.3485 - accuracy: 0.1114 - val_loss: 2.2935 - val_accuracy: 0.1126
Epoch 2/10
157/157 [==============================] - 7s 45ms/step - loss: 2.2547 - accuracy: 0.1422 - val_loss: 2.2193 - val_accuracy: 0.1682
Epoch 3/10
157/157 [==============================] - 7s 44ms/step - loss: 2.1546 - accuracy: 0.2130 - val_loss: 2.1147 - val_accuracy: 0.2258
Epoch 4/10
157/157 [==============================] - 7s 45ms/step - loss: 2.0281 - accuracy: 0.2596 - val_loss: 1.9960 - val_accuracy: 0.2639
Epoch 5/10
157/157 [==============================] - 7s 44ms/step - loss: 1.9433 - accuracy: 0.2816 - val_loss: 1.9487 - val_accuracy: 0.2812
Epoch 6/10
157/157 [==============================] - 5s 30ms/step - loss: 1.8719 - accuracy: 0.3106 - val_loss: 1.9179 - val_accuracy: 0.2843
Epoch 7/10
157/157 [==============================] - 5s 31ms/step - loss: 1.8128 - accuracy: 0.3280 - val_loss: 1.8818 - val_accuracy: 0.310

In [ ]:
early_stopping = EarlyStopping(patience= 5,  monitor='loss')
model.fit(X_train[:5000], y_train[:5000], epochs=100, callbacks=[early_stopping], validation_data=(X_train, y_train))

Epoch 1/100
157/157 [==============================] - 6s 37ms/step - loss: 1.6388 - accuracy: 0.3960 - val_loss: 1.9042 - val_accuracy: 0.3169
Epoch 2/100
157/157 [==============================] - 7s 44ms/step - loss: 1.6115 - accuracy: 0.4092 - val_loss: 1.8927 - val_accuracy: 0.3232
Epoch 3/100
157/157 [==============================] - 7s 45ms/step - loss: 1.5679 - accuracy: 0.4264 - val_loss: 1.9033 - val_accuracy: 0.3265
Epoch 4/100
157/157 [==============================] - 4s 28ms/step - loss: 1.5196 - accuracy: 0.4446 - val_loss: 1.9378 - val_accuracy: 0.3323
Epoch 5/100
157/157 [==============================] - 5s 32ms/step - loss: 1.4877 - accuracy: 0.4568 - val_loss: 1.9357 - val_accuracy: 0.3295
Epoch 6/100
157/157 [==============================] - 4s 29ms/step - loss: 1.4611 - accuracy: 0.4708 - val_loss: 1.9475 - val_accuracy: 0.3289
Epoch 7/100
157/157 [==============================] - 5s 30ms/step - loss: 1.4135 - accuracy: 0.4890 - val_loss: 1.9510 - val_accuracy:

In [ ]:
model.evaluate(X_train,y_train)

1250/1250 [==============================] - 4s 3ms/step - loss: 3.7793 - accuracy: 0.4290


[3.7793116569519043, 0.4290499985218048]

In [ ]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 4ms/step - loss: 8.7740 - accuracy: 0.1010


[8.773971557617188, 0.10100000351667404]

In [ ]:
tf.keras.backend.clear_session()
tf.random.set_seed(42)

In [ ]:
model = Sequential()

model.add(Flatten(input_shape=[32,32,3]))
model.add(tf.keras.layers.BatchNormalization())

for _ in range(20):
  model.add(Dense(100, activation='swish', kernel_initializer='he_normal'))
model.add(Dense(10, activation='softmax'))

In [ ]:
optimizer = tf.keras.optimizers.Nadam(learning_rate=5e-5)
model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
model.fit(X_train[:5000], y_train[:5000],epochs=10, validation_data=(X_train, y_train))

Epoch 1/10
157/157 [==============================] - 17s 51ms/step - loss: 2.2966 - accuracy: 0.1334 - val_loss: 2.2996 - val_accuracy: 0.1666
Epoch 2/10
157/157 [==============================] - 5s 31ms/step - loss: 2.2185 - accuracy: 0.1948 - val_loss: 2.1500 - val_accuracy: 0.2218
Epoch 3/10
157/157 [==============================] - 7s 45ms/step - loss: 2.0696 - accuracy: 0.2376 - val_loss: 2.0266 - val_accuracy: 0.2607
Epoch 4/10
157/157 [==============================] - 5s 30ms/step - loss: 1.9579 - accuracy: 0.2756 - val_loss: 1.9608 - val_accuracy: 0.2788
Epoch 5/10
157/157 [==============================] - 7s 45ms/step - loss: 1.8864 - accuracy: 0.3070 - val_loss: 1.9219 - val_accuracy: 0.2961
Epoch 6/10
157/157 [==============================] - 7s 45ms/step - loss: 1.8103 - accuracy: 0.3356 - val_loss: 1.8959 - val_accuracy: 0.3061
Epoch 7/10
157/157 [==============================] - 5s 33ms/step - loss: 1.7444 - accuracy: 0.3512 - val_loss: 1.8738 - val_accuracy: 0.315

In [ ]:
model.evaluate(X_train,y_train)

1250/1250 [==============================] - 4s 3ms/step - loss: 3.7793 - accuracy: 0.4290


[3.7793116569519043, 0.4290499985218048]

In [ ]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 8.7740 - accuracy: 0.1010


[8.773971557617188, 0.10100000351667404]

In [ ]:
model = Sequential()
model.add(Flatten(input_shape=[32,32,3]))
model.add(tf.keras.layers.BatchNormalization())
for _ in range(20):
  model.add(Dense(100, activation='selu',kernel_initializer='lecun_normal'))
model.add(Dense(10, activation='softmax'))
optimizer = tf.keras.optimizers.Nadam(learning_rate=5e-5)
model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
model.fit(X_train[:5000], y_train[:5000],epochs=10, validation_data=(X_train, y_train))

Epoch 1/10
157/157 [==============================] - 15s 38ms/step - loss: 2.2643 - accuracy: 0.1920 - val_loss: 2.1423 - val_accuracy: 0.2364
Epoch 2/10
157/157 [==============================] - 7s 44ms/step - loss: 1.9458 - accuracy: 0.2992 - val_loss: 1.9355 - val_accuracy: 0.3018
Epoch 3/10
157/157 [==============================] - 5s 33ms/step - loss: 1.8377 - accuracy: 0.3314 - val_loss: 1.8842 - val_accuracy: 0.3215
Epoch 4/10
157/157 [==============================] - 7s 44ms/step - loss: 1.7492 - accuracy: 0.3766 - val_loss: 1.8506 - val_accuracy: 0.3375
Epoch 5/10
157/157 [==============================] - 7s 44ms/step - loss: 1.6883 - accuracy: 0.3852 - val_loss: 1.8071 - val_accuracy: 0.3580
Epoch 6/10
157/157 [==============================] - 4s 28ms/step - loss: 1.6196 - accuracy: 0.4190 - val_loss: 1.8028 - val_accuracy: 0.3555
Epoch 7/10
157/157 [==============================] - 7s 44ms/step - loss: 1.5639 - accuracy: 0.4408 - val_loss: 1.7718 - val_accuracy: 0.370

In [ ]:
early_stopping = EarlyStopping(patience= 5, monitor='loss')
model.fit(X_train[:5000], y_train[:5000], epochs=100, callbacks=[early_stopping], validation_data=(X_train, y_train))

Epoch 1/100
157/157 [==============================] - 8s 48ms/step - loss: 1.3350 - accuracy: 0.5240 - val_loss: 1.7895 - val_accuracy: 0.3852
Epoch 2/100
157/157 [==============================] - 7s 44ms/step - loss: 1.2895 - accuracy: 0.5436 - val_loss: 1.7854 - val_accuracy: 0.3933
Epoch 3/100
157/157 [==============================] - 5s 32ms/step - loss: 1.2511 - accuracy: 0.5444 - val_loss: 1.8126 - val_accuracy: 0.3908
Epoch 4/100
157/157 [==============================] - 4s 29ms/step - loss: 1.1914 - accuracy: 0.5820 - val_loss: 1.8132 - val_accuracy: 0.3963
Epoch 5/100
157/157 [==============================] - 5s 30ms/step - loss: 1.1548 - accuracy: 0.6010 - val_loss: 1.7973 - val_accuracy: 0.4096
Epoch 6/100
157/157 [==============================] - 7s 45ms/step - loss: 1.1039 - accuracy: 0.6090 - val_loss: 1.8518 - val_accuracy: 0.3963
Epoch 7/100
157/157 [==============================] - 4s 29ms/step - loss: 1.0492 - accuracy: 0.6372 - val_loss: 1.8464 - val_accuracy:

In [ ]:
model.evaluate(X_train,y_train)

1250/1250 [==============================] - 4s 3ms/step - loss: 3.7793 - accuracy: 0.4290


[3.7793116569519043, 0.4290499985218048]

In [ ]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 8.7740 - accuracy: 0.1010


[8.773971557617188, 0.10100000351667404]

In [ ]:
tf.random.set_seed(42)

In [ ]:
y_probas = np.stack([model(X_test, training=True)
                    for sample in range(100)])
y_proba = y_probas.mean(axis=0)

In [ ]:
model.predict(X_test[:1]).round(3)

1/1 [==============================] - 0s 270ms/step


array([[0.   , 0.   , 0.   , 0.001, 0.999, 0.   , 0.   , 0.   , 0.   ,
        0.   ]], dtype=float32)

In [ ]:
y_proba[0].round(3)

array([0.   , 0.   , 0.   , 0.001, 0.999, 0.   , 0.   , 0.   , 0.   ,
       0.   ], dtype=float32)

In [ ]:
y_std = y_probas.std(axis=0)
y_std[0].round(3)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

1000.0

In [ ]:
tf.random.set_seed(42)
# selu da outdopout ist elemek olmaz, alpha dropout olar
model = Sequential()
model.add(Flatten(input_shape=[32,32,3]))

for _ in range(20):
  model.add(Dense(100, activation='selu', kernel_initializer='lecun_normal'))
model.add(Dense(10, activation='softmax'))
